<?php

namespace AdminBundle\Repository;

/**
 * BorrowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BorrowRepository extends \Doctrine\ORM\EntityRepository
{
}
