<?php

namespace CommonBundle\Repository;

/**
 * BorrowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BorrowRepository extends \Doctrine\ORM\EntityRepository
{

  public function findCurrentBorrowings($currentDate) {
    return $this
      ->createQueryBuilder('b')
      ->select(array('b'))
      ->where("b.endDate < :currentDate")
      ->setParameter('currentDate', $currentDate)
      ->getQuery()
      ->getResult();
  }

  public function findEndedBorrowings($currentDate) {
    return $this
      ->createQueryBuilder('b')
      ->select(array('b'))
      ->where("b.endDate >= :currentDate")
      ->setParameter('currentDate', $currentDate)
      ->getQuery();
  }
}
