<?php

namespace CommonBundle\Repository;

/**
 * CongestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CongestionRepository extends \Doctrine\ORM\EntityRepository
{
  public function getAllIds()
  {
      return $this
      ->createQueryBuilder('c')
      ->select('c.id')
      ->getQuery()
      ->getArrayResult();
  }
}
