<?php

namespace CommonBundle\Repository;

/**
 * CopyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CopyRepository extends \Doctrine\ORM\EntityRepository
{
  public function getCopiesByGame($game)
 {
    return $this
      ->createQueryBuilder('c')
      ->select('c')
      ->where("c.game = :game")
      ->setParameter('game', $game)
      ->getQuery()
      ->getArrayResult();

  }

}
