<?php

namespace CommonBundle\Repository;

/**
 * CopyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CopyRepository extends \Doctrine\ORM\EntityRepository
{

  public function countCopiesByGame($gameid) {
    return $this
      ->createQueryBuilder('c')
      ->select('COUNT(c)')
      ->where('c.game = :gameid')
      ->setParameter('gameid', '%'.$gameid.'%')
      ->getQuery()
      ->getSingleScalarResult();
  }


}
