<?php

namespace CommonBundle\Repository;

/**
 * MembershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembershipRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMaxByMember($member){

        $result = $this->createQueryBuilder('ms')
            ->select('MAX(ms.beginDate)')
            ->where('ms.member= :member')
            ->setParameter('member', $member)
            ->getQuery()
            ->getSingleResult();


        return $result;
    }

}
