<?php

namespace CommonBundle\Repository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends \Doctrine\ORM\EntityRepository
{
  public function getAllTypesById()
  {
      return $this
      ->createQueryBuilder('t')
      ->select('id')
      ->getQuery()
      ->getArrayResult();
  }
}
